import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { resolve } from 'path'
import path from "path"

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [react()], // to process SFC
    resolve: {
        alias: {
            "@": path.resolve(__dirname, "./src"),
        },
    },
    build: {
        lib: {
            entry: resolve(__dirname, 'src/index.ts'),
            name: 'sui-react',
            formats: ['es'], // adding 'umd' requires globals set to every external module
            fileName: format => `sui-react.${format}.js`,
        },
        rollupOptions: {
            // external modules won't be bundled into your library
            external: ['react', 'react-dom'],
            output: {
                // disable warning on src/index.ts using both default and named export
                exports: 'named',
                globals: {
                    react: 'React',
                    'react-dom': 'ReactDOM',
                },
                assetFileNames: assetInfo => assetInfo.name === 'style.css' ? 'style.min.css' : assetInfo.name
            }
        },
        sourcemap: true,
        emptyOutDir: false, // to retain the types folder generated by tsc
    }
})
